[project]
authors = [{name = "Lachlan Hurst", email = "lachlan.hurst@gmail.com"}]
dependencies = []
name = "so100-mujoco-rl"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-64", "win-64", "osx-arm64", "linux-64"]

[tool.pixi.pypi-dependencies]
so100_mujoco_rl = { path = ".", editable = true }

[tool.pixi.tasks]
main = { cmd = "python src/so100_mujoco_rl/main.py" }
